In [1]:
import os
os.chdir('/Users/Halmagyi/Documents/Programming/Python/geo/BoundingBox')

In [53]:
import numpy.random as  random
import time

from importlib import reload
import boundingbox.boundingbox; reload(boundingbox.boundingbox)
from boundingbox.boundingbox import *
import boundingbox.distances; reload(boundingbox.distances)
from boundingbox.distances import *
from haversine import haversine

from boundingbox.settings import *

paris = (48.8566, 2.3522)
vincennes = (48.8283, 2.4330)
boulogne = (48.8624, 2.2492)
st_denis = (48.9362, 2.3574)
orleans = (47.9030, 1.9093)
places_paris = np.array([vincennes, boulogne, st_denis, orleans])

suva = (18.1248, 178.4501)
wallis = (13.2959, -176.2057)
tubuo = (18.2356, -178.8107)
labasa = (16.4308, 179.3630)
places_suva = [wallis, tubuo, labasa]

norlisk = (69.3558, 88.1893)
alert = (82.5018, 62.3481)
barneo = (89.5250, -30.4500)
bronlundhus = (82.17166598, -30.667663996)
nagurskoye = (80.8107, 47.6499)
russkoye = (71.1333, 149.2667)
sachsharbour = (71.9851, 125.2465)
places_alert = [norlisk, barneo, bronlundhus, nagurskoye, russkoye, sachsharbour]



In [83]:
# testing get_all_points_within_distance

N=2
pts = get_points_within_distance(paris, places_paris, 7)
print(pts)

[[array([48.8283,  2.433 ]) 6.698235303709655]]


In [81]:
pts[:,1]

array([6.698235303709655, 7.562627816217736, 8.859287406231937,
       110.96572196425218], dtype=object)

In [80]:
pts_2 = np.load("tests/resources/paris_distances_200.npy")

np.array_equal(pts_2,pts)

False

In [ ]:
# testing get_closest_N_points




In [ ]:
targets= [[(48.8283, 2.433), 6.698235303709655],[(48.8624, 2.2492), 7.562627816217736],[(48.9362, 2.3574), 8.859287406231937]]
closest_points_are_within_length(targets, 3, 8.859287406231937)


The haversine formula is

$$\sin^2 \left(\frac{d}{2R}\right) = \sin^2\left(\frac{\varphi_2-\varphi_1}{2}\right) + \cos \varphi_1 \cos \varphi_2 \sin^2\left(\frac{\lambda_2-\lambda_1}{2}\right)$$

or equivalently

$$
\cos \left(\frac{d}{R}\right) = \sin \varphi_1 \sin \varphi_2  + \cos (\lambda_1 - \lambda_2)\cos \varphi_1 \cos \varphi_2 
$$

where the (lat, lon) of two points are
$$p_1 = (\varphi_1,\lambda_1)\,,\quad p_2 = (\varphi_2,\lambda_2)$$
and are bounded by
$$ -\frac{\pi}{2} \leq \varphi \leq \frac{\pi}{2}$$
$$ -\pi \leq \lambda \leq \pi$$

Note that the python package haversine takes degrees as the default arguments


If two latitudes are equal, $\varphi_1=\varphi_2=\varphi$ then

$$d = 2 R \, \sin^{-1} \cos \varphi \sin \left(\frac{\lambda_2-\lambda_1}{2}\right)$$

$$\Rightarrow \quad |\lambda_2-\lambda_1| = 2\left|\sin^{-1}\left[ \frac{\sin\left(\frac{d}{2R}\right)}{\cos(\varphi)}\right]\right|$$ 

When two longitudes are equal we have

$$\varphi_2-\varphi_1 = \frac{d}{R}$$

We want a bounding box centered on $(\varphi_0, \lambda_0)$ of edge-size 2L.

$$\lambda_{east} = \lambda_0 + 2\left|\sin^{-1}\left[ \frac{\sin\left(\frac{L}{2R}\right)}{\cos(\varphi_0)}\right]\right|$$
$$\lambda_{west} = \lambda_0 - 2\left|\sin^{-1}\left[ \frac{\sin\left(\frac{L}{2R}\right)}{\cos(\varphi_0)}\right]\right|$$
$$\varphi_{north} = \varphi_0 + \frac{L}{R}$$
$$\varphi_{north} = \varphi_0 - \frac{L}{R}$$

In [ ]:
1==1 and not 1==2

In [ ]:
N=1
bbox_length = make_bounding_box_length(suva, places_suva, N)


boundingbox = BoundingBox(suva, 100)
print(boundingbox.bbox)
print(bbox_length)
get_closest_N_points(suva, places_suva, N, 100)


In [ ]:
2/3

In [ ]:
0==0.0

In [ ]:
d = {}
d['FRONT']={'north':1, 'south':3}
d['REVERSE']={'north':2, 'south':4}

In [ ]:
for k,v in d.items():
    print(k,v)

In [ ]:
ll=[]
l2 = np.array([[1,2],[3,4]])
ll+l2

# alert

In [12]:
norlisk = (69.3558, 88.1893)
alert = (82.5018, 62.3481)
barneo = (89.5250, -30.4500)
bronlundhus = (82.17166598, -30.667663996)
nagurskoye = (80.8107, 47.6499)
russkoye = (71.1333, 149.2667)
sachsharbour = (71.9851, 125.2465)
places_alert = np.array([norlisk, barneo, bronlundhus, nagurskoye, russkoye, sachsharbour])

distances_alert = [haversine(alert, place) for place in places_alert]
distances_alert

[1585.506606607707,
 837.9940181254185,
 1234.878022045599,
 301.2233268867223,
 2209.747109426272,
 1779.855407043432]

In [13]:
N=3
boundingbox = BoundingBox(alert, 100)
print(boundingbox.bbox)
get_closest_points(alert, places_alert, N, 1300)


{'front': {'north': 83.40112160591873, 'south': 81.60247839408127, 'east': 69.25615658653567, 'west': 55.44004341346434}}
boundingbox.bbox:  {'reverse': {'east': -90.0, 'west': 90.0, 'north': 90.0, 'south': 81.00422457211346}, 'front': {'east': 90.0, 'west': -90.0, 'north': 90.0, 'south': 70.8106191230565}}
east < west:  [[ 69.3558      88.1893    ]
 [ 89.525      -30.45      ]
 [ 82.17166598 -30.667664  ]
 [ 80.8107      47.6499    ]
 [ 71.1333     149.2667    ]
 [ 71.9851     125.2465    ]]
targets_filtered:  [array([ 89.525, -30.45 ]), array([ 82.17166598, -30.667664  ])]
west < east:  [[ 69.3558      88.1893    ]
 [ 89.525      -30.45      ]
 [ 82.17166598 -30.667664  ]
 [ 80.8107      47.6499    ]
 [ 71.1333     149.2667    ]
 [ 71.9851     125.2465    ]]
targets_filtered:  [array([ 89.525, -30.45 ]), array([ 82.17166598, -30.667664  ]), array([ 89.525, -30.45 ]), array([ 82.17166598, -30.667664  ]), array([80.8107, 47.6499])]


array([[array([80.8107, 47.6499]), 301.2233268867223],
       [array([ 89.525, -30.45 ]), 837.9940181254185],
       [array([ 89.525, -30.45 ]), 837.9940181254185]], dtype=object)

In [23]:
print(places_alert)
bbox = {'reverse': {'east': -90.0, 'west': 90.0, 'north': 90.0, 'south': 81.00422457211346}, 'front': {'east': 90.0, 'west': -90.0, 'north': 90.0, 'south': 70.8106191230565}}
def target_in_bounding_box_front(target, bbox):
    return (target[0] >= bbox[SOUTH]) & (target[0] <= bbox[NORTH]) & (target[1] >= bbox[WEST]) & (target[1] <= bbox[EAST])

def target_in_bounding_box_reverse(target, bbox):
    return 1 == (target[0] >= bbox[SOUTH]) & (target[0] <= bbox[NORTH]) & ~((target[1] >= bbox[EAST]) & (target[1] <= bbox[WEST]))

    
print(target_in_bounding_box_front(np.transpose(places_alert), bbox[FRONT]))
print(target_in_bounding_box_reverse(np.transpose(places_alert), bbox[REVERSE]))


[[ 69.3558      88.1893    ]
 [ 89.525      -30.45      ]
 [ 82.17166598 -30.667664  ]
 [ 80.8107      47.6499    ]
 [ 71.1333     149.2667    ]
 [ 71.9851     125.2465    ]]
[False  True  True  True False False]
[False False False False False False]


In [15]:
places_alert

array([[ 69.3558    ,  88.1893    ],
       [ 89.525     , -30.45      ],
       [ 82.17166598, -30.667664  ],
       [ 80.8107    ,  47.6499    ],
       [ 71.1333    , 149.2667    ],
       [ 71.9851    , 125.2465    ]])

In [ ]:
# distance from alert to the north pole
haversine(alert, (90, 0))

In [ ]:
alert

In [ ]:
haversine(alert, (90, 0))

In [ ]:
haversine((85.02036896289921, 0), (90, 0))

In [ ]:
N=2

boundingbox = BoundingBox(alert, 1000)

print(boundingbox.bbox)
get_closest_N_points(alert, places_alert, N, 1000)


In [ ]:
{'reverse': {'east': -90.0, 'west': 90.0, 'north': 90.0, 'south': 73.6554533217098}, 'front': {'east': 90.0, 'west': -90.0, 'north': 90.0, 'south': 64.5621212895553}}


In [ ]:
bbox_1 = {'east': -90.0, 'west': 90.0, 'north': 90.0, 'south': 73.6554533217098}
bbox_2 = {'east': 90.0, 'west': -90.0, 'north': 90.0, 'south': 64.5621212895553}


In [ ]:
def func(latlon, minlat, maxlat, minlon, maxlon):
    return (latlon[0] >= minlat) & (latlon[0] <= maxlat) & (latlon[1] >= minlon) & (latlon[1] <= maxlon) 
bbox = bbox_2
targets = np.transpose(np.array([nagurskoye, nagurskoye, nagurskoye]))
func(targets, bbox[SOUTH], bbox[NORTH], bbox[WEST], bbox[EAST])

In [ ]:
def target_in_bounding_box_front(target, bbox):
    return (target[0] >= bbox[SOUTH]) & (target[0] <= bbox[NORTH]) & \
            (target[1] >= bbox[WEST]) & (target[1] <= bbox[EAST])

targets = np.array([nagurskoye, nagurskoye, nagurskoye])
print(targets)
targets[target_in_bounding_box_front(np.transpose(targets), bbox)]

In [ ]:
targets.reshape(2,3)

In [ ]:
(1>0) & ~((2>1) & (2>3))

In [ ]:
True & (False & True)

# Large Random Target set

In [26]:
N = 10**6
lats = (180 * (random.random(N)-1/2)).reshape(N,1)
lons = (360 * (random.random(N)-1/2)).reshape(N,1)
targets = np.concatenate([lats, lons], axis=1)

In [31]:
N=4
bbox_length = make_bounding_box_length(paris, targets, N)
print(bbox_length)
start = time.time()
pts = get_closest_points(paris, targets, N, 30)
print(time.time()-start)
print(pts)

2813.3693634728893
0.032294273376464844
[[array([48.8236226 ,  2.27171725]) 6.938258155111937]
 [array([48.95410407,  2.44080835]) 12.628966498124754]
 [array([48.74570065,  2.25252166]) 14.330501106273678]
 [array([48.84791785,  2.13746012]) 15.741432622785931]]


In [ ]:
bbox = {'reverse': {'east': -90.0, 'west': 90.0, 'north': 90.0, 'south': 39.156748256370705}, 'front': {'east': 90.0, 'west': -90.0, 'north': 90.0, 'south': -12.750277357138522}}

def target_in_bounding_box_front(target, bbox):
    return (target[0] >= bbox[SOUTH]) & (target[0] <= bbox[NORTH]) & (target[1] >= bbox[WEST]) & (target[1] <= bbox[EAST])

def target_in_bounding_box_reverse(target, bbox):
    return 1 == (target[0] >= bbox[SOUTH]) & (target[0] <= bbox[NORTH]) & ~((target[1] >= bbox[WEST]) & (target[1] <= bbox[EAST]))


print(target_in_bounding_box_front(paris, bbox[FRONT]))
print(target_in_bounding_box_front(paris, bbox[REVERSE]))
print(target_in_bounding_box_reverse(paris, bbox[FRONT]))
print(target_in_bounding_box_reverse(paris, bbox[REVERSE]))


In [30]:
N=4
bbox_length = make_bounding_box_length(paris, targets, N)
print(bbox_length)
start = time.time()
pts = get_closest_points(paris, targets, N, bbox_length)
print(time.time()-start)
print(pts)

2813.3693634728893
0.4313070774078369
[[array([48.8236226 ,  2.27171725]) 6.938258155111937]
 [array([48.95410407,  2.44080835]) 12.628966498124754]
 [array([48.74570065,  2.25252166]) 14.330501106273678]
 [array([48.84791785,  2.13746012]) 15.741432622785931]]


In [39]:
targets_dist = pts
targets_dist[1] > 10

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [49]:
arr1 = np.array([1,2,3,4,5]).reshape(5,1)
arr2 = np.array([6,7,8,9,10]).reshape(5,1)
arr3 = np.transpose(np.concatenate([arr1, arr2], axis=1))
arr3[1] > 7

array([False, False,  True,  True,  True])

In [52]:
targets_dist_tr = np.transpose(targets_dist)
targets_dist[targets_dist_tr[1]>10]

array([[array([48.95410407,  2.44080835]), 12.628966498124754],
       [array([48.74570065,  2.25252166]), 14.330501106273678],
       [array([48.84791785,  2.13746012]), 15.741432622785931]],
      dtype=object)